// Checks that no implicit paths are generated by the `#[bitfield]` proc. macro
// and `#[derive(BitfieldSpecifier)]` derive macro.

use ::modular_bitfield::prelude::*;

#[bitfield]
pub struct PrimitivesBitfield {
    a: bool,
    b: u8,
    c: u16,
    d: u32,
    e: u64,
    f: u128,
    rest: B7,
}

fn main() {}
